import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  textbookSidebar: [
    {
      type: 'html',
      value: '<span class="sidebar-title">Theory</span>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: '📖 Full Textbook',
      collapsible: true,
      collapsed: false, // Start with the textbook open
      items: [
        {type: 'doc', id: 'textbook/introduction', label: 'Introduction'},
        {type: 'doc', id: 'textbook/chapter-1-foundations', label: 'Chapter 1: Foundations'},
        {type: 'doc', id: 'textbook/chapter-2-robot-hardware', label: 'Chapter 2: Hardware'},
        {type: 'doc', id: 'textbook/chapter-3-kinematics-dynamics', label: 'Chapter 3: Kinematics & Dynamics'},
        {type: 'doc', id: 'textbook/chapter-4-control-systems', label: 'Chapter 4: Control'},
        {type: 'doc', id: 'textbook/chapter-5-perception', label: 'Chapter 5: Perception'},
        {type: 'doc', id: 'textbook/chapter-6-planning', label: 'Chapter 6: Planning'},
        {type: 'doc', id: 'textbook/chapter-7-reinforcement-learning', label: 'Chapter 7: RL Theory'},
        {type: 'doc', id: 'textbook/chapter-8-slam-nav', label: 'Chapter 8: SLAM'},
        {type: 'doc', id: 'textbook/chapter-9-humanoid-robotics', label: 'Chapter 9: Humanoids'},
        {type: 'doc', id: 'textbook/chapter-10-ethics', label: 'Chapter 10: Ethics'},
      ],
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<span class="sidebar-title">Application</span>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: '📚 Learning Modules',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'module-1-ros2'},
        {type: 'autogenerated', dirName: 'module-2-digital-twin'},
        {type: 'autogenerated', dirName: 'module-3-ai-brain'},
        {type: 'autogenerated', dirName: 'module-4-vla'},
        {type: 'autogenerated', dirName: 'module-5-locomotion'},
        {type: 'autogenerated', dirName: 'module-6-manipulation'},
        {type: 'autogenerated', dirName: 'module-7-hri'},
      ],
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<span class="sidebar-title">Practice</span>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: '🧪 Engineering Labs',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'labs'},
      ],
    },
  ],
};

export default sidebars;