import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  textbookSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [{type: 'autogenerated', dirName: 'module-1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [{type: 'autogenerated', dirName: 'module-2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain',
      items: [{type: 'autogenerated', dirName: 'module-3-ai-brain'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [{type: 'autogenerated', dirName: 'module-4-vla'}],
    },
  ],
};

export default sidebars;