openapi: 3.0.0
info:
  title: Translation API
  version: 1.0.0
paths:
  /api/translate:
    post:
      summary: Translate markdown content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: Markdown content to translate
                targetLanguage:
                  type: string
                  enum: [ur, hi]
                  description: Target language code (Urdu or Hindi)
      responses:
        '200':
          description: Successful translation
          content:
            application/json:
              schema:
                type: object
                properties:
                  translatedContent:
                    type: string
        '500':
          description: Translation failed
